backend = "xrender";

vsync = true;

frame-opacity = 1.0;

fading = false;
fade-in-step = 0.00;
fade-out-step = 0.00;

opacity-rule = [
    "80:class_g = 'Alacritty'",
    "80:class_g = 'Ghostty'",
];

shadow = true;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.30;

blur-method = "dual_kawase";
blur-strength = 12;
blur-background = true;

detect-rounded-corners = false;

use-damage = true;

wintypes: {
    tooltip = { fade = true; shadow = true; };
    dock = { shadow = false; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 1.0; };
    dropdown_menu = { opacity = 1.0; };
};
