#wallpaper {
#    monitor =
#    path = $HOME/Downloads/wallpaper.jpg
#    fit_mode  = cover
#}
wallpaper {
    monitor =
    path = $HOME/Wallpapers/mount_fuji.jpg
    fit_mode  = fill
}
splash = false
